[tool.poetry]
name = "tombulled-annotate"
version = "0.1.14"
description = "Python Annotation System Inspired by Java Annotations"
authors = ["Tom Bulled <26026015+tombulled@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tombulled/annotate"
repository = "https://github.com/tombulled/annotate"
keywords = ["python", "annotate", "annotation", "marker", "label", "mark", "tag"]
packages = [
    {include = "annotate"}
]

[tool.poetry.dependencies]
python = "^3.8"
attribute = "^0.1.4"
typing-extensions = "^4.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true